-- 코드를 입력하세요
SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID,  R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE B.CREATED_DATE BETWEEN '2022-10-01'AND '2022-10-31'
    AND R.BOARD_ID = B.BOARD_ID
ORDER BY R.CREATED_DATE, B.TITLE;